### Recuperar todas las pelis
GET http://localhost:8080/movies

### Recuperar una peli por ID
GET http://localhost:8080/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf

###R Recuperar todas las pelis por genero
GET http://localhost:8080/movies?genre=adventure

### Crear una pelicula
POST http://localhost:8080/movies
Content-Type: application/json

{
    "title" : "The Good Father",
    "year" : 1975,
    "director" : "Francis Ford Coppola",
    "duration" : 175,
    "poster" : "https://img.fruugo.com/product/4/49/14441494_max.jpg",
    "genre" :["Crime", "Drama"]
}

### Actualizar una pelicula
PATCH  http://localhost:8080/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
    "year" : 2002
}

